[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
logfile_maxbytes=10MB

[program:flask_main]
command=gunicorn --bind=0.0.0.0:8000 --timeout 600 --workers=2 app:app
directory=/home/site/wwwroot
autostart=true
autorestart=true
stdout_logfile=/tmp/flask_main.log
stderr_logfile=/tmp/flask_main.err.log
environment=PYTHONUNBUFFERED="1"

[program:mcp_server]
command=gunicorn --bind=0.0.0.0:9000 --timeout 600 --workers=2 "mcp_server.server:app"
directory=/home/site/wwwroot
autostart=true
autorestart=true
stdout_logfile=/tmp/mcp_server.log
stderr_logfile=/tmp/mcp_server.err.log
environment=PYTHONUNBUFFERED="1"